server:
  port: 8003 # 服务端口号
#spring相关配置
spring:
  application:
    name: ADMIN-PROVIDE # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questionnairesystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhaohongyu001110
    druid:
      testWhileIdle: true
      validationQuery: SELECT 1

#redis相关配置
redis:
  host: 127.0.0.1
  port: 6379
  database: QuestionnaireSystem
  password:
  timeout: 10000
  jedis:
    pool:
      max-active: 8
      max-wait: -1ms
      max-idle: 8
      min-idle: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka/,http://eureka7001.com:7001/eureka/
#mybatisplus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      field-strategy: not_empty
      db-type: mysql
      table-prefix: sys_
      column-underline: true
      refresh-mapper: true